# INSTANCE SETTINGS FILE
print('[CONFIG] imported instance.config')

# APP SECRET
SECRET_KEY = 'Iw4nilrNMIYuhsSBQxnxhj0ntOPCjA3Ydmia4li4w4s'

# DB SETTINGS
SQLALCHEMY_DATABASE_URI = 'sqlite:///test.db'

# MAIL SETTINGS
MAIL_SERVER = 'localhost'
MAIL_PORT = 8025
MAIL_USE_TLS = None
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
ADMINS = ['admin@test.de']

# LOG SETTINGS
LOG_DIR = 'logs'

# APP SETTINGS
ENABLE_LOGIN = True
ENABLE_REGISTRATION = True
ENABLE_PASSWORD_RESET = True

CONFIRM_REGISTRATION = True
MAIL_ON_CONFIRMATION = True
LOGIN_ON_CONFIRMATION = True
