"""user account deletion

Revision ID: 284f958dcca0
Revises: 43b90c39d857
Create Date: 2020-08-15 18:03:11.213383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284f958dcca0'
down_revision = '43b90c39d857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('deleted_on')

    # ### end Alembic commands ###
